from typing import Protocol
from .schemas import Profile, ProfileAuthRegister, ProfileOAuthRegister, ProfileUpdate, ProfileOnboard
from uuid import UUID


class ExternalProfileService(Protocol):
    def register_profile(
        self, *, profile_id: UUID, profile_new: ProfileAuthRegister | ProfileOAuthRegister
    ) -> None: ...
    def get_profile(self, *, profile_id: UUID) -> Profile: ...
    def oauth_process_profile(self, *, profile_id: UUID, profile_new: ProfileOAuthRegister) -> None: ...
    def onboard_profile(self, *, profile_id: UUID, profile_update: ProfileOnboard) -> None: ...
    def check_onboarding_status(self, *, profile_id: UUID) -> bool: ...
    def complete_onboard(self, *, profile_id: UUID) -> None: ...


class InternalProfileService(ExternalProfileService, Protocol):
    def update_profile(self, *, profile_id: UUID, profile_update: ProfileUpdate) -> None: ...
