from .models import Auth, AuthSession
from .schemas import AuthRegister, AuthPasswordUpdate, OAuthOutcome, OAuthRegister
from uuid import UUID
from authlib.integrations.starlette_client import OAuth
from fastapi.requests import Request
from typing import Protocol


class InternalAuthService(Protocol):
    def login(self, *, email: str, password: str) -> Auth: ...

    def retrieve_auth_by_session(self, *, session_id: str) -> Auth: ...

    def register_web(self, *, auth_in: AuthRegister) -> Auth: ...

    def register_oauth(self, *, auth_in: OAuthRegister) -> Auth: ...

    def create_session(self, *, auth: Auth) -> AuthSession: ...

    def change_password(self, *, user_id: UUID, auth_pw_in: AuthPasswordUpdate) -> None: ...

    async def process_oauth_callback(self, oauth: OAuth, request: Request) -> OAuthOutcome: ...
